### ISSUE TITLE
Mixin error, game crashing

### ISSUE THREAD

**Issue by MOMIN5** [3arthqu4ke/PingBypass#22]
crashing before startup, i also have all the mixins files im not sure what is causing the crash, here is the crash on console 

`[main/FATAL] [mixin]: Mixin apply failed mixins.pingbypass.json:minecraft.gui.IContainer -> net.minecraft.inventory.Container: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching field_75150_e:S in net/minecraft/inventory/Container for mixins.pingbypass.json:minecraft.gui.IContainer->@Accessor[FIELD_SETTER]::setTransactionID(S)V`

then

`[main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2768-universal.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2768-universal.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/inventory/Container
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_275]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_275]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_275]
        at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_275]
        at net.minecraft.entity.EntityList.func_191303_a(EntityList.java:410) ~[vi.class:?]
        at net.minecraft.entity.EntityList.func_151514_a(EntityList.java:317) ~[vi.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:505) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]`

**Comment by MOMIN5** [comment]
crashing before startup

**Comment by 3arthqu4ke** [comment]
You are trying to run the MinecraftServer, but for PingBypass you need to run the Client.
