### ISSUE TITLE
Does not run in forge server

### ISSUE THREAD

**Issue by italoaa** [3arthqu4ke/PingBypass#33]
[20:05:55] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2854.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/inventory/Container

**Comment by italoaa** [comment]
What's your twitter or discord?

**Comment by IkegamiI** [comment]
Ikegami#3283 add me. Im tryin to figure this out too

**Comment by 3arthqu4ke** [comment]
You need the Minecraft Client not the server.

**Comment by italoaa** [comment]
I have tried running the client but I do not know how to make the GUI work Can I msg u through discord?

**Comment by 3arthqu4ke** [comment]
I recommend using this: https://github.com/3arthqu4ke/HeadlessForge

**Comment by italoaa** [comment]
![image](https://user-images.githubusercontent.com/72895337/114942483-391d1180-9e0a-11eb-81a5-1a6afc62715e.png)
this is my logs after using the headless forge. The file Server.json did no show up so I created it and filled it but it did not work.

this are some more logs before the last ones
![image](https://user-images.githubusercontent.com/72895337/114942818-b8124a00-9e0a-11eb-9ff8-ae72be0ad53e.png)

this is what it says 
![image](https://user-images.githubusercontent.com/72895337/114942999-f90a5e80-9e0a-11eb-95d8-8475e0136688.png)

**Comment by 3arthqu4ke** [comment]
Moved [to](https://github.com/3arthqu4ke/PingBypass/issues/35).
