### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by proxyo1** [3arthqu4ke/PingBypass#36]
when its using the default server.json minecraft works but when i change ip and port it crashes, is there any fix?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Core (pingbypass-1.0.0-release.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 5/5/21 4:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PingBypass (pingbypass)
Caused by: java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:461)
	at sun.nio.ch.Net.bind(Net.java:453)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.4.0-1046-azure
	Java Version: 1.8.0_292, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 411856752 bytes (392 MB) / 728236032 bytes (694 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                                  | Signature                                |
	|:----- |:---------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft  | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHI  | mcp        | 9.42         | minecraft.jar                           | None                                     |
	| LCHI  | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2855-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge      | 14.23.5.2855 | forge-1.12.2-14.23.5.2855-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | pingbypass | 1.0.0        | pingbypass-1.0.0-release.jar            | None                                     |

	Loaded coremods (and transformers): 
Core (pingbypass-1.0.0-release.jar)
  
	GL info: ' Vendor: 'VMware, Inc.' Version: '3.1 Mesa 20.0.8' Renderer: 'llvmpipe (LLVM 10.0.0, 256 bits)'

**Comment by 3arthqu4ke** [comment]
You need to put in the Internal IP of your VPS. Just google how to find that one on the OS you are using. The port needs to be opened for Traffic and not in use.

**Comment by proxyo1** [comment]
my ip and port is set perfectly, it just crashes on launch, when its on default 127.0.0.1 it dosent crash
