### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by VanVVA** [3arthqu4ke/PingBypass#37]
Everytime I launch the launcher with the pingbypass in the mods folder, it crashes, Is there any way I can fix this?

**Comment by 3arthqu4ke** [comment]
I need the crashlog.

**Comment by VanVVA** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Core (pingbypass-1.0.0-release.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 5/18/21 5:41 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PingBypass (pingbypass)
Caused by: java.net.BindException: Cannot assign requested address: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)

**Comment by 3arthqu4ke** [comment]
- Your Server.json isn't configured properly. The IServerIP should be set to the internal IP of the server you are trying to run PingBypass on. Finding it is different from OS to OS, maybe your VPS provider allows you to set it. 
  - Also make sure that the Port you are trying to use is not used by other programs and is opened in the firewall.

**Comment by VanVVA** [comment]
Thank you, I got it working now

**Comment by 3arthqu4ke** [comment]
Nice!
