### ISSUE TITLE
Me and friends tying to setup pingbypass

### ISSUE THREAD

**Issue by NotTolon** [3arthqu4ke/PingBypass#4]
were aall a bit braindead but were au and need pingbypass

we have a windows vps but whenever we launch Minecraft on it we get the same log

i knoww this isnt related to the mod but pls help

it also says shit about pixels before the launcher update it was talking about pixel and gll in craash reason

[21:50:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:50:21] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:50:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:50:21] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[21:50:21] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64
[21:50:22] [main/INFO] [FML]: Searching C:\Users\Administrator\AppData\Roaming\.minecraft\mods for mods
[21:50:22] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from pingbypass-1.0.0-release_2.jar
[21:50:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:50:22] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:50:22] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Administrator/AppData/Roaming/.minecraft/mods/pingbypass-1.0.0-release_2.jar Service=LaunchWrapper Env=CLIENT
[21:50:22] [main/WARN] [FML]: The coremod me.earth.pingbypass.mixin.Core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:50:22] [main/WARN] [FML]: The coremod Core (me.earth.pingbypass.mixin.Core) is not signed!
[21:50:22] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[21:50:22] [main/ERROR] [mixin]: Mixin config mixins.pingbypass.json does not specify "minVersion" property
[21:50:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:50:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:50:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:50:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:50:33] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[21:50:33] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[21:50:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:50:33] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[21:50:33] [main/ERROR] [mixin]: Mixin config mixins.pingbypass.json does not specify "minVersion" property
[21:50:33] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@545607f2
[21:50:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:50:41] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:50:41] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:50:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:50:41] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:50:51] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:51:04] [Client thread/INFO] [net.minecraft.client.Minecraft]: Setting user: SniffGlue

**Comment by wawddd** [comment]
p

**Comment by 123321ssd** [comment]
p

**Comment by CRTCTY** [comment]
-I don't see an error message in the log you sent there. -> is that all?
-I can't really tell what the "it was talking about pixel and gll in craash reason" part means without seeing it. -> provide more?
-Can you try to run a minecraft 1.16 version on the VPS? Would be good to know if those work for you.
-I reckon that the issue has to do with no GPU being present, I had similar issues on my VM, but mine was running on Debian.

**Comment by 3arthqu4ke** [comment]
-I can't see an error message in the log you sent. -> is there more?
-I can't really tell what the "it was talking about pixel and gll in craash reason" without seeing it -> screenshot?
-Please try to run a 1.16 minecraft version. If that one works I have an idea in which direction this could be going.
I reckon this has to do with no GPU being present.

**Comment by notperry1** [comment]
> -I can't see an error message in the log you sent. -> is there more?
> -I can't really tell what the "it was talking about pixel and gll in craash reason" without seeing it -> screenshot?
> -Please try to run a 1.16 minecraft version. If that one works I have an idea in which direction this could be going.
> I reckon this has to do with no GPU being present.

there is no gpu lmao

**Comment by 3arthqu4ke** [comment]
No my VPS has no GPU either, that is not the issue, just running minecraft on the integrated one can be tricky.

**Comment by TerikKek** [comment]
use openGL

**Comment by TerikKek** [comment]
also use a linux server as it is easier to get minecraft running on their intergrated graphics

**Comment by NotTolon** [comment]
Here is the crash report

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PingBypass (pingbypass)
Caused by: java.lang.StackOverflowError
	at io.netty.channel.nio.NioEventLoop$4.run(NioEventLoop.java:173)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:166)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:51)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
	at com.github.steveice10.packetlib.tcp.TcpConnectionListener.bind(TcpConnectionListener.java:66)
	at com.github.steveice10.packetlib.Server.bind(Server.java:56)
	at me.earth.pingbypass.server.PhobosServer.bind(PhobosServer.java:97)
	at me.earth.pingbypass.server.PhobosServer.createServer(PhobosServer.java:90)
	at me.earth.pingbypass.server.PhobosServer.bind(PhobosServer.java:102)
	at me.earth.pingbypass.server.PhobosServer.createServer(PhobosServer.java:90)
	at me.earth.pingbypass.server.PhobosServer.bind(PhobosServer.java:102)
	at me.earth.pingbypass.server.PhobosServer.createServer(PhobosServer.java:90)
	at me.earth.pingbypass.server.PhobosServer.bind(PhobosServer.java:102)
	at me.earth.pingbypass.server.PhobosServer.createServer(PhobosServer.java:90)
	at me.earth.pingbypass.server.PhobosServer.bind(PhobosServer.java:102)
	at me.earth.pingbypass.server.PhobosServer.createServer(PhobosServer.java:90)
	at me.earth.pingbypass.server.PhobosServer.bind(PhobosServer.java:102)

**Comment by 3arthqu4ke** [comment]
Use the newest version, I just fixed some stuff.
Also ensure that you use an open port that is not being used.

**Comment by TerikKek** [comment]
my game was having trouble aswell so make sure that you install the latest version of openGL
